PUT {{host}}/api/v1/cars/5
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "id": 5,
  "premium": true,
  "hand_number": 1,
  "equipments": {
    "outside":[
      "sunroof"
    ]
  },
  "options":{
    "premium":[
      "had_accident",
      "technical_check_ok"
    ]
  }
}
